name: Basic Workflow Dispatch Example

on:
  workflow_dispatch:
    inputs:
      jdk-list:
        description: 'JDK version to run against'
        required: true
        default: '17'


jobs:
  build:
    strategy:
      matrix:
        jdk-version: ${{ inputs.jdk-list }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.jdk-version }}

